FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /src
RUN ls -la /
COPY ./src /src

RUN dotnet restore "LoanOffers.sln"
RUN dotnet build "LoanOffers.sln"
RUN dotnet test *.Tests.Unit/*.Tests.Unit.csproj

FROM build AS publish
RUN dotnet publish "LoanOffers.sln" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "LoanOffers.Api.dll"]