name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: dir
      run: cd src
    - name: ls
      run: ls   
    - name: Install dependencies
      run:  dotnet restore ./src/LoanOffers.sln
    - name: Build
      run:  dotnet build ./src/LoanOffers.sln --configuration Release --no-restore
    - name: Test
      run:  dotnet test ./srs/LoanOffers.sln --no-restore --verbosity normal
